name: Run Tests

on:
  push:
    branches: [dev]  # Run tests when code is pushed to "dev"
  pull_request:
    branches: [dev]  # Run tests when a PR is opened for "dev"

jobs:
  test:
    runs-on: ubuntu-latest  # Use an Ubuntu machine

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Gets your code

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build and Run Tests
      run: |
        mvn clean test  # Runs Maven tests (for Jakarta EE)
